/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Colores semánticos usando las variables CSS
        border: "var(--border)",
        'border-strong': "var(--border-strong)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: {
          DEFAULT: "var(--background)",
          secondary: "var(--background-secondary)",
          tertiary: "var(--background-tertiary)",
        },
        foreground: {
          DEFAULT: "var(--foreground)",
          secondary: "var(--foreground-secondary)",
          muted: "var(--foreground-muted)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          foreground: "var(--primary-foreground)",
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          hover: "var(--secondary-hover)",
          foreground: "var(--secondary-foreground)",
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          hover: "var(--destructive-hover)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
          border: "var(--card-border)",
        },
        // Colores de estado
        success: {
          DEFAULT: "var(--color-success-500)",
          hover: "var(--color-success-600)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
        },
        warning: {
          DEFAULT: "var(--color-warning-500)",
          hover: "var(--color-warning-600)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
        },
        error: {
          DEFAULT: "var(--color-error-500)",
          hover: "var(--color-error-600)",
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
        },
        info: {
          DEFAULT: "var(--color-info-500)",
          hover: "var(--color-info-600)",
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
        },
        // Escala de grises
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
          950: "var(--color-gray-950)",
        },
      },
      spacing: {
        'xs': "var(--spacing-xs)",
        'sm': "var(--spacing-sm)",
        'md': "var(--spacing-md)",
        'lg': "var(--spacing-lg)",
        'xl': "var(--spacing-xl)",
        '2xl': "var(--spacing-2xl)",
        '3xl': "var(--spacing-3xl)",
      },
      borderRadius: {
        'none': "var(--radius-none)",
        'sm': "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        'md': "var(--radius-md)",
        'lg': "var(--radius-lg)",
        'xl': "var(--radius-xl)",
        '2xl': "var(--radius-2xl)",
        '3xl': "var(--radius-3xl)",
        'full': "var(--radius-full)",
      },
      boxShadow: {
        'sm': "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        'md': "var(--shadow-md)",
        'lg': "var(--shadow-lg)",
        'xl': "var(--shadow-xl)",
        '2xl': "var(--shadow-2xl)",
        'inner': "var(--shadow-inner)",
      },
      fontFamily: {
        'sans': "var(--font-family-sans)",
        'mono': "var(--font-family-mono)",
      },
      fontSize: {
        'xs': "var(--font-size-xs)",
        'sm': "var(--font-size-sm)",
        'base': "var(--font-size-base)",
        'lg': "var(--font-size-lg)",
        'xl': "var(--font-size-xl)",
        '2xl': "var(--font-size-2xl)",
        '3xl': "var(--font-size-3xl)",
        '4xl': "var(--font-size-4xl)",
        '5xl': "var(--font-size-5xl)",
        '6xl': "var(--font-size-6xl)",
      },
      fontWeight: {
        'light': "var(--font-weight-light)",
        'normal': "var(--font-weight-normal)",
        'medium': "var(--font-weight-medium)",
        'semibold': "var(--font-weight-semibold)",
        'bold': "var(--font-weight-bold)",
        'extrabold': "var(--font-weight-extrabold)",
      },
      lineHeight: {
        'tight': "var(--line-height-tight)",
        'normal': "var(--line-height-normal)",
        'relaxed': "var(--line-height-relaxed)",
      },
      transitionDuration: {
        'fast': "150ms",
        'normal': "300ms",
        'slow': "500ms",
      },
      transitionTimingFunction: {
        'ease-in': "var(--ease-in)",
        'ease-out': "var(--ease-out)",
        'ease-in-out': "var(--ease-in-out)",
      },
      zIndex: {
        'dropdown': "var(--z-dropdown)",
        'sticky': "var(--z-sticky)",
        'fixed': "var(--z-fixed)",
        'modal-backdrop': "var(--z-modal-backdrop)",
        'modal': "var(--z-modal)",
        'popover': "var(--z-popover)",
        'tooltip': "var(--z-tooltip)",
        'toast': "var(--z-toast)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}